"""
Adversarial Variant Generator  (Phase 3)

Consumes a SecurityInvariant and produces a bounded, deterministic set of
AdversarialVariant records.  Each variant is an independently-executable
verification scenario with full provenance.

This module is a TEST-DESCRIPTION GENERATOR only.
It does NOT execute HTTP requests.
It does NOT apply patches.
It does NOT bypass the human-approval gate.

The generated variants are intended to be passed to the existing
VerificationEngine for execution.

Safety boundaries enforced by this module:
- Routes are only sourced from the SecurityInvariant or from repository
  api_routes already indexed by the RepositoryAgent.
- No external URL construction.
- No destructive HTTP methods (DELETE / PUT / PATCH) generated by default.
- No credentials stored in variant records.
- Generation is deterministic: same inputs → same outputs (no random ordering).
- Generation is bounded: count comes from available scenario/repository data,
  not from a fixed marketing number.
"""
import re
from typing import List, Optional, Tuple

from app.models import (
    AdversarialVariant,
    ExploitCheckOutcome,
    Investigation,
    OracleExpectedOutcome,
    SecurityInvariant,
    VariantGenerationResult,
    VariantProvenance,
    VariantType,
    VulnerabilityClass,
)

# ── Safety: methods that are never generated unless the invariant explicitly
#    marks them as read-only-safe.
_DESTRUCTIVE_METHODS = {"DELETE", "PUT", "PATCH"}

# ── Max identifier distance used in identifier variants.
#    Adjacent IDs only — no wide enumeration.
_IDENTIFIER_ADJACENT_DISTANCE = 1


class VariantGenerator:
    """
    Generates a bounded set of AdversarialVariants from a SecurityInvariant.

    Entry point:
        result = VariantGenerator().generate(investigation)

    The generator reads:
    - invariant.attack               → original-attack variant + identifier dimension
    - invariant.oracle               → expected_oracle for all variants
    - invariant.legitimate_use       → identity dimension (owner actor)
    - invariant.scope.routes         → route context for sibling-route discovery
    - investigation.repository_info  → api_routes for sibling-route discovery

    It does NOT invent routes, identities, or oracles.
    """

    # ─────────────────────────────────────────────────────────────────────────
    # Public API
    # ─────────────────────────────────────────────────────────────────────────

    def generate(self, investigation: Investigation) -> VariantGenerationResult:
        """
        Generate all supported variants for the investigation's SecurityInvariant.

        Returns a VariantGenerationResult with:
        - variants (supported=True and supported=False)
        - supported_count / skipped_count
        - skipped_reasons (audit trail)
        - unsupported_dimensions (generation decisions)
        """
        invariant = investigation.security_invariant

        if invariant is None:
            return VariantGenerationResult(
                source_invariant_id="",
                generation_note="No SecurityInvariant present on this investigation.",
                unsupported_dimensions=[
                    "original_attack", "identity", "identifier",
                    "sibling_route", "request_variant",
                ],
            )

        if not invariant.supported:
            return VariantGenerationResult(
                source_invariant_id=invariant.id,
                generation_note=(
                    f"SecurityInvariant is not supported "
                    f"({invariant.unsupported_reason or 'no reason given'}). "
                    "No variants can be generated."
                ),
                unsupported_dimensions=[
                    "original_attack", "identity", "identifier",
                    "sibling_route", "request_variant",
                ],
            )

        # Only BOLA is supported in Phase 3
        if invariant.vulnerability_class != VulnerabilityClass.BOLA:
            return VariantGenerationResult(
                source_invariant_id=invariant.id,
                generation_note=(
                    f"Variant generation for {invariant.vulnerability_class.value} "
                    "is not yet implemented.  Phase 3 supports BOLA only."
                ),
                unsupported_dimensions=[
                    "original_attack", "identity", "identifier",
                    "sibling_route", "request_variant",
                ],
            )

        api_routes = (
            investigation.repository_info.api_routes
            if investigation.repository_info else []
        )

        all_variants: List[AdversarialVariant] = []
        skipped_reasons: List[str] = []
        unsupported_dimensions: List[str] = []

        # ── Dimension 1: Original attack (always first) ───────────────────────
        original = self._generate_original_attack(invariant)
        all_variants.append(original)

        # ── Dimension 2: Identity variants ────────────────────────────────────
        identity_variants, identity_skipped = self._generate_identity_variants(invariant)
        all_variants.extend(identity_variants)
        skipped_reasons.extend(identity_skipped)
        if not identity_variants:
            unsupported_dimensions.append(
                "identity — no alternate non-owner actor inferable from invariant"
            )

        # ── Dimension 3: Identifier variants ──────────────────────────────────
        id_variants, id_skipped = self._generate_identifier_variants(invariant)
        all_variants.extend(id_variants)
        skipped_reasons.extend(id_skipped)
        if not id_variants and id_skipped:
            unsupported_dimensions.append(id_skipped[0] if id_skipped else "identifier")

        # ── Dimension 4: Sibling-route variants ────────────────────────────────
        sibling_variants, sibling_skipped = self._generate_sibling_route_variants(
            invariant, api_routes
        )
        all_variants.extend(sibling_variants)
        skipped_reasons.extend(sibling_skipped)
        if not sibling_variants:
            unsupported_dimensions.append(
                "sibling_route — no related routes discovered from repository metadata"
            )

        # ── Dimension 5: Request variants (safe read-only mutations) ──────────
        req_variants, req_skipped = self._generate_request_variants(invariant)
        all_variants.extend(req_variants)
        skipped_reasons.extend(req_skipped)
        if not req_variants and req_skipped:
            unsupported_dimensions.append(
                "request_variant — no safe read-only alternate representations available"
            )

        supported = [v for v in all_variants if v.supported]
        skipped = [v for v in all_variants if not v.supported]

        return VariantGenerationResult(
            source_invariant_id=invariant.id,
            variants=all_variants,
            supported_count=len(supported),
            skipped_count=len(skipped),
            skipped_reasons=skipped_reasons,
            unsupported_dimensions=unsupported_dimensions,
            generation_note=(
                f"Generated {len(supported)} executable variant(s) and "
                f"recorded {len(skipped)} skipped variant(s) from "
                f"SecurityInvariant {invariant.id} "
                f"({invariant.vulnerability_class.value} / {invariant.cwe or 'no CWE'})."
            ),
        )

    # ─────────────────────────────────────────────────────────────────────────
    # Dimension 1 — Original attack
    # ─────────────────────────────────────────────────────────────────────────

    def _generate_original_attack(self, invariant: SecurityInvariant) -> AdversarialVariant:
        """
        Re-package the invariant's primary attack scenario as a typed variant.
        This is the baseline: the attack that was originally identified.
        """
        attack = invariant.attack
        blocked = invariant.oracle.blocked_outcome

        return AdversarialVariant(
            source_invariant_id=invariant.id,
            variant_type=VariantType.ORIGINAL_ATTACK,
            description=(
                "Primary attack scenario from the SecurityInvariant.  "
                "A non-owner authenticated user requests a resource they do not own.  "
                "After a correct fix this must be blocked."
            ),
            actor_role="non_owner",
            actor_credential_hint=attack.actor_credential_hint or (
                "Use attacker credentials from invariant.attack.auth_credentials (scenario data)"
            ),
            route=attack.route_example,
            method=attack.method.upper(),
            parameters={
                "_note": "Scenario data from SecurityInvariant.attack.parameters",
                **attack.parameters,
            },
            expected_oracle=blocked,
            expected_oracle_label=blocked.label if blocked else "attack_blocked",
            provenance=VariantProvenance(
                source="security_invariant",
                parent_route=attack.route_template or attack.route_example,
                reason=(
                    "Direct lift of the primary attack scenario from the SecurityInvariant.  "
                    "Used as the baseline exploit-replay variant."
                ),
                invariant_id=invariant.id,
            ),
            limitations=(
                "Tests the single primary attack path only.  "
                "Does not cover sibling routes or alternate actors."
            ),
        )

    # ─────────────────────────────────────────────────────────────────────────
    # Dimension 2 — Identity variants
    # ─────────────────────────────────────────────────────────────────────────

    def _generate_identity_variants(
        self, invariant: SecurityInvariant
    ) -> Tuple[List[AdversarialVariant], List[str]]:
        """
        Produce variants that exercise the same route with different actors.

        Sources actors from:
        1. invariant.legitimate_use  — the owner (used as a positive/regression check)
        2. invariant.scope.actor_roles — role names explicitly listed in the invariant

        Generates:
        - alternate_non_owner if the invariant's legitimate_use has a second entry
          (i.e. a second non-owner user is implicitly known from scenario data)

        Does NOT invent arbitrary users.
        """
        variants: List[AdversarialVariant] = []
        skipped: List[str] = []
        attack = invariant.attack
        blocked = invariant.oracle.blocked_outcome

        # Check whether invariant scope lists an "alternate" non-owner role
        roles = invariant.scope.actor_roles
        has_alternate = "non_owner" in roles and len(invariant.legitimate_use) >= 2

        if not has_alternate:
            skipped.append(
                "identity (alternate_non_owner) — invariant does not define a second "
                "non-owner actor; cannot generate alternate identity variant without "
                "inventing users"
            )
            return variants, skipped

        # The second legitimate_use entry carries a second actor's credential hint
        # (per the BOLA invariant builder in root_cause.py which adds an
        #  unauthenticated use-case as the second entry — that's a different dimension)
        # Only produce an identity variant if the second entry has credentials.
        second_uc = invariant.legitimate_use[1]
        if not second_uc.auth_credentials:
            skipped.append(
                "identity (alternate_non_owner) — second legitimate_use entry has no "
                "credentials; cannot generate an executable alternate-identity variant"
            )
            return variants, skipped

        variants.append(AdversarialVariant(
            source_invariant_id=invariant.id,
            variant_type=VariantType.IDENTITY,
            description=(
                "Alternate non-owner actor test.  A second known non-owner user "
                "requests the same target resource.  After a correct fix this must "
                "also be blocked — the ownership check must not be user-specific."
            ),
            actor_role="alternate_non_owner",
            actor_credential_hint=(
                "Use alternate credentials from invariant.legitimate_use[1].auth_credentials "
                "(scenario data)"
            ),
            route=attack.route_example,
            method=attack.method.upper(),
            parameters={"_note": "Scenario data — alternate non-owner actor"},
            expected_oracle=blocked,
            expected_oracle_label=blocked.label if blocked else "attack_blocked",
            provenance=VariantProvenance(
                source="identity_dimension",
                parent_route=attack.route_example,
                reason=(
                    "Verifies that the ownership check is role-based, not username-specific.  "
                    "A second known non-owner must also be blocked."
                ),
                invariant_id=invariant.id,
            ),
            limitations=(
                "Only tests the single additional non-owner actor available from scenario data.  "
                "Does not exhaustively enumerate all possible actors."
            ),
        ))

        return variants, skipped

    # ─────────────────────────────────────────────────────────────────────────
    # Dimension 3 — Identifier variants
    # ─────────────────────────────────────────────────────────────────────────

    def _generate_identifier_variants(
        self, invariant: SecurityInvariant
    ) -> Tuple[List[AdversarialVariant], List[str]]:
        """
        Produce variants that exercise the same route with adjacent/known identifiers.

        Only generates when:
        - The route_example contains a numeric identifier that can be analysed.
        - The adjacent ID is not the same as the attacker's own resource
          (to avoid generating a legitimate-access variant here).

        Does NOT enumerate: only produces at most one adjacent-ID variant.
        """
        variants: List[AdversarialVariant] = []
        skipped: List[str] = []

        attack = invariant.attack
        blocked = invariant.oracle.blocked_outcome

        # Extract numeric ID from the attack route_example
        numeric_id, route_pattern = _extract_numeric_id(attack.route_example)

        if numeric_id is None:
            skipped.append(
                "identifier — route_example does not contain a numeric ID; "
                "safe identifier mutation is not possible"
            )
            return variants, skipped

        # Try the adjacent ID (one step away)
        adjacent_id = numeric_id + _IDENTIFIER_ADJACENT_DISTANCE

        # Guard: if the owner's route_example has the same adjacent ID,
        # this would become an owner-access test, not an attacker variant.
        owner_ids = set()
        for uc in invariant.legitimate_use:
            owner_numeric, _ = _extract_numeric_id(uc.route_example)
            if owner_numeric is not None:
                owner_ids.add(owner_numeric)

        if adjacent_id in owner_ids:
            # Try one step in the other direction
            alternate_id = numeric_id - _IDENTIFIER_ADJACENT_DISTANCE
            if alternate_id > 0 and alternate_id not in owner_ids:
                adjacent_id = alternate_id
            else:
                skipped.append(
                    f"identifier (adjacent_id={adjacent_id}) — this ID matches "
                    "an owner resource; skipped to avoid colliding with the "
                    "legitimate-use dimension"
                )
                return variants, skipped

        adjacent_route = route_pattern.format(id=adjacent_id)

        variants.append(AdversarialVariant(
            source_invariant_id=invariant.id,
            variant_type=VariantType.IDENTIFIER,
            description=(
                f"Adjacent-identifier variant.  Non-owner requests resource "
                f"at adjacent ID ({adjacent_id}) instead of the primary attack ID.  "
                "Ownership enforcement must be consistent across IDs."
            ),
            actor_role="non_owner",
            actor_credential_hint=(
                "Use attacker credentials from invariant.attack.auth_credentials (scenario data)"
            ),
            route=adjacent_route,
            method=attack.method.upper(),
            parameters={
                "_note": "Identifier dimension — adjacent resource ID",
                "base_attack_id": numeric_id,
                "variant_id_value": adjacent_id,
            },
            expected_oracle=blocked,
            expected_oracle_label=blocked.label if blocked else "attack_blocked",
            provenance=VariantProvenance(
                source="identifier_dimension",
                parent_route=attack.route_example,
                reason=(
                    f"Tests that ownership enforcement is consistent for ID {adjacent_id} "
                    f"(adjacent to primary attack ID {numeric_id}).  "
                    "A BOLA fix that only protects a specific ID would fail this variant."
                ),
                invariant_id=invariant.id,
            ),
            limitations=(
                "Tests one adjacent ID only.  Not an enumeration scan.  "
                "The adjacent ID may not exist in the target application's database — "
                "a 404 response would be classified as ERROR, not PASS."
            ),
        ))

        return variants, skipped

    # ─────────────────────────────────────────────────────────────────────────
    # Dimension 4 — Sibling route variants
    # ─────────────────────────────────────────────────────────────────────────

    def _generate_sibling_route_variants(
        self,
        invariant: SecurityInvariant,
        api_routes: List[str],
    ) -> Tuple[List[AdversarialVariant], List[str]]:
        """
        Discover related routes from repository API metadata and produce variants.

        Only routes that:
        1. Share a common path prefix with the primary attack route
        2. Are explicitly listed in repository_info.api_routes (no invention)
        3. Are not identical to the primary attack route
        4. Use a safe HTTP method (GET only by default)
        5. Are not in the invariant's scope.routes (already covered by original)

        are considered.

        The ID placeholder in the sibling route is filled with the same scenario
        data ID from the primary attack route_example.
        """
        variants: List[AdversarialVariant] = []
        skipped: List[str] = []

        attack = invariant.attack
        blocked = invariant.oracle.blocked_outcome

        primary_route = attack.route_example
        primary_template = attack.route_template or ""

        # Extract the resource prefix (e.g. "/api/resources" from "/api/resources/2")
        prefix = _extract_route_prefix(primary_route)
        if not prefix:
            skipped.append(
                "sibling_route — could not determine route prefix from primary attack route"
            )
            return variants, skipped

        # Extract the numeric ID from the primary attack route for substitution
        numeric_id, _ = _extract_numeric_id(primary_route)

        # Collect already-covered routes
        covered = set(invariant.scope.routes)
        if primary_route:
            covered.add(primary_route)
        if primary_template:
            covered.add(primary_template)

        seen_routes: set = set()

        for route_entry in api_routes:
            # api_routes are stored as "METHOD /path" by the RepositoryAgent
            parts = route_entry.split(None, 1)
            if len(parts) < 2:
                continue
            method_str, path = parts[0].upper(), parts[1]

            # Only GET for sibling-route variants by default
            if method_str in _DESTRUCTIVE_METHODS:
                skipped.append(
                    f"sibling_route {path} — method {method_str} is destructive; skipped"
                )
                continue

            # Must share the resource prefix
            if not path.startswith(prefix):
                continue

            # Skip the primary route itself (both template and example forms)
            if path == primary_route or path == primary_template:
                continue

            # Skip routes already covered
            if path in covered:
                continue

            # Resolve path parameters using scenario data (numeric_id from attack)
            resolved_path, is_parameterised = _resolve_path_params(path, numeric_id)

            if resolved_path in seen_routes:
                continue
            seen_routes.add(resolved_path)

            # Determine oracle — sibling routes that share the same resource
            # should use the same blocked_outcome from the invariant oracle.
            # If we can't determine an oracle, mark as unsupported.
            if blocked is None:
                var = AdversarialVariant(
                    source_invariant_id=invariant.id,
                    variant_type=VariantType.SIBLING_ROUTE,
                    description=(
                        f"Sibling route {method_str} {resolved_path} discovered in repository.  "
                        "Cannot determine expected outcome — no blocked_outcome in oracle."
                    ),
                    actor_role="non_owner",
                    actor_credential_hint=(
                        "Use attacker credentials from invariant.attack.auth_credentials"
                    ),
                    route=resolved_path,
                    method=method_str,
                    supported=False,
                    unsupported_reason="No blocked_outcome defined in SecurityOracle",
                    provenance=VariantProvenance(
                        source="repository_api_routes",
                        parent_route=primary_route,
                        reason=f"Same resource scope as {primary_route}",
                        invariant_id=invariant.id,
                    ),
                )
                skipped.append(
                    f"sibling_route {resolved_path} — no oracle blocked_outcome; marked unsupported"
                )
                variants.append(var)
                continue

            variants.append(AdversarialVariant(
                source_invariant_id=invariant.id,
                variant_type=VariantType.SIBLING_ROUTE,
                description=(
                    f"Sibling route test: {method_str} {resolved_path}.  "
                    f"Related to primary route {primary_route} — same resource scope.  "
                    "If ownership enforcement was only applied to the primary route, "
                    "this sibling may remain vulnerable."
                ),
                actor_role="non_owner",
                actor_credential_hint=(
                    "Use attacker credentials from invariant.attack.auth_credentials (scenario data)"
                ),
                route=resolved_path,
                method=method_str,
                parameters={
                    "_note": "Sibling route — scenario ID from primary attack",
                    "resolved_from_template": is_parameterised,
                    "original_path_template": path,
                },
                expected_oracle=blocked,
                expected_oracle_label=blocked.label,
                provenance=VariantProvenance(
                    source="repository_api_routes",
                    parent_route=primary_route,
                    reason=(
                        f"Discovered in repository api_routes; shares resource prefix '{prefix}' "
                        f"with primary attack route {primary_route}.  "
                        "Tests whether ownership enforcement was applied consistently."
                    ),
                    invariant_id=invariant.id,
                ),
                limitations=(
                    f"The oracle expects the same blocked codes as the primary route "
                    f"({blocked.allowed_status_codes}).  If the sibling route uses different "
                    "semantics (e.g. always returns 404 for missing resources), the result "
                    "may be classified as ERROR rather than PASS."
                ),
            ))

        return variants, skipped

    # ─────────────────────────────────────────────────────────────────────────
    # Dimension 5 — Request variants (safe read-only mutations)
    # ─────────────────────────────────────────────────────────────────────────

    def _generate_request_variants(
        self, invariant: SecurityInvariant
    ) -> Tuple[List[AdversarialVariant], List[str]]:
        """
        Produce safe alternate request representations of the primary attack.

        Currently supported:
        - Malformed identifier: route with a non-numeric ID where a numeric one
          is expected.  Tests that the server's error path does not accidentally
          bypass the auth check.

        Does NOT generate:
        - Alternative HTTP methods (HEAD, OPTIONS, etc.) — not meaningful for BOLA
        - Destructive methods (DELETE/PUT/PATCH)
        - Arbitrary query-string mutations
        """
        variants: List[AdversarialVariant] = []
        skipped: List[str] = []

        attack = invariant.attack
        blocked = invariant.oracle.blocked_outcome

        numeric_id, route_pattern = _extract_numeric_id(attack.route_example)

        if numeric_id is None:
            skipped.append(
                "request_variant (malformed_id) — primary route has no numeric ID; "
                "malformed-identifier variant is not applicable"
            )
            return variants, skipped

        # Malformed ID: substitute a non-numeric sentinel
        malformed_route = route_pattern.format(id="INVALID")

        # The expected outcome for a malformed ID is ambiguous (might return 422/404)
        # — we cannot safely apply the same blocked_outcome oracle.
        # Mark as unsupported with a clear reason.
        variants.append(AdversarialVariant(
            source_invariant_id=invariant.id,
            variant_type=VariantType.REQUEST_VARIANT,
            description=(
                f"Malformed identifier variant: {attack.method.upper()} {malformed_route}.  "
                "Tests that a non-numeric ID in the path does not accidentally bypass "
                "authentication checks.  Expected response is a 4xx validation error, "
                "not a 200 with resource data."
            ),
            actor_role="non_owner",
            actor_credential_hint=(
                "Use attacker credentials from invariant.attack.auth_credentials (scenario data)"
            ),
            route=malformed_route,
            method=attack.method.upper(),
            parameters={
                "_note": "Request variant — malformed path parameter",
                "base_attack_id": numeric_id,
                "malformed_value": "INVALID",
            },
            expected_oracle=None,  # Cannot safely apply the BOLA oracle to a malformed ID
            expected_oracle_label="",
            supported=False,
            unsupported_reason=(
                "The BOLA oracle expects HTTP 403/404 for a blocked attack, but a malformed "
                "path ID typically returns HTTP 422 (Unprocessable Entity) from FastAPI's "
                "type validation layer — before any ownership check runs.  "
                "Applying the blocked_outcome oracle would produce a false ERROR result.  "
                "Manual inspection recommended."
            ),
            provenance=VariantProvenance(
                source="request_variant_dimension",
                parent_route=attack.route_example,
                reason=(
                    "Tests that type-validation failure does not accidentally expose data.  "
                    "A correctly implemented endpoint must reject the malformed ID before "
                    "running any database query."
                ),
                invariant_id=invariant.id,
            ),
            limitations=(
                "Marked unsupported because the oracle cannot distinguish a correct "
                "422 validation response from a security failure without additional "
                "oracle configuration.  Future work: add a malformed_id_outcome to the oracle."
            ),
        ))

        return variants, skipped


# ─────────────────────────────────────────────────────────────────────────────
# Module-level helpers (pure functions — independently testable)
# ─────────────────────────────────────────────────────────────────────────────

def _extract_numeric_id(route: str) -> Tuple[Optional[int], str]:
    """
    Extract the first numeric segment from a concrete route URL.

    Returns (numeric_id, format_pattern) where format_pattern is the route
    with the numeric segment replaced by {id} for safe substitution.

    Examples:
        "/api/resources/2"           → (2, "/api/resources/{id}")
        "/api/resources/2/sub"       → (2, "/api/resources/{id}/sub")
        "/api/resources"             → (None, "")
        "/api/resources/{resource_id}" → (None, "")  ← template, not example
    """
    match = re.search(r'/(\d+)(/|$)', route)
    if not match:
        return None, ""
    numeric_id = int(match.group(1))
    # Replace the matched numeric segment with {id}
    pattern = route[:match.start()] + "/{id}" + route[match.end() - len(match.group(2)):]
    return numeric_id, pattern


def _extract_route_prefix(route: str) -> str:
    """
    Extract the resource-level prefix from a concrete route.

    For a route like "/api/resources/2" returns "/api/resources".
    For "/api/resources/2/sub" returns "/api/resources".
    For "/api/resources" (no ID) returns "/api/resources".
    For "" returns "".

    The prefix is used to identify sibling routes in the same resource scope.
    """
    if not route:
        return ""
    # Remove numeric segments and anything after them
    match = re.search(r'/\d+', route)
    if match:
        return route[:match.start()]
    # No numeric ID — the entire route is the prefix (strip trailing slash)
    return route.rstrip("/")


def _resolve_path_params(path: str, numeric_id: Optional[int]) -> Tuple[str, bool]:
    """
    Replace path parameter placeholders ({param_name}) with the scenario ID.

    Returns (resolved_path, was_parameterised).

    If no placeholders exist, returns (path, False).
    If numeric_id is None, replaces with "1" as a safe fallback.
    """
    if "{" not in path:
        return path, False
    replacement = str(numeric_id) if numeric_id is not None else "1"
    resolved = re.sub(r'\{[^}]+\}', replacement, path)
    return resolved, True
